### ISSUE TITLE
coilpack.fallback route?

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/Coilpack#3]
What exactly is this route for? I was having trouble with Publisher when Coilpack was installed and traced it back to this line of code that I added way back in Coilpack alpha version. I originally had it checking to see if the route was `null`, but now it looks like there is a `coilpack.fallback` value. What I think I need to do here is know if a custom Laravel route is active, and if so return false so Publisher doesn't try to perform any redirects or modify the URL.

```
// If there is a valid custom route defined in Coilpack, e.g. /graphiql, let Laravel handle it.
        if(ee()->has('coilpack')) {
            $route = app('router')->currentRouteName();

            if ($route !== null && $route !== 'coilpack.fallback') {
                return true;
            }
        }
```

**Comment by bryannielsen** [comment]
@litzinger Coilpack's 'fallback' route is triggered when there aren't any matching Laravel routes and is how we're passing the request off to EE's routing.  I think your code looks good for returning `true` if a custom route is matched that isn't our fallback route.  We previously hadn't given it a name but thought this was a helpful change to identify the fallback route.  Sorry this wasn't called out in the changelog I didn't realize the impact it would have

**Comment by litzinger** [comment]
No worries, I implemented that back when Coilpack was in alpha.
