### ISSUE TITLE
Can't login to CP due to invalid cookie time error

### ISSUE THREAD

**Issue by litzinger** [ExpressionEngine/Coilpack#6]
I haven't been using Coilpack for a couple of months, then needed to test some functionality with it so I started routing EE through it (before I was bypassing Coilpack). I started getting this error when trying to access the CP. Since it had been awhile since I've updated, I deleted my Coilpack instance, re-installed so Coilpack is up-to-date, and then updated EE to 7.3.14 from 7.3.11, and I'm still getting the error. I've tried deleting all my cookies but nothing works.

<img width="1634" alt="Screenshot 2023-11-26 at 5 26 46 AM" src="https://github.com/ExpressionEngine/Coilpack/assets/53965/16096391-441e-45ca-9317-df7243b20c5d">
<img width="1617" alt="Screenshot 2023-11-26 at 5 47 32 AM" src="https://github.com/ExpressionEngine/Coilpack/assets/53965/6fe53e18-daec-464b-af5b-193a9a6c5c07">

**Comment by lleake** [comment]
Had this issue popup as well in a functioning local dev install on Mac OSX 14.1.1, using Herd, after an upgrade to php 8.2.13 in the Herd interface. Laravel side of the app still seems to be working.  EECMS side is throwing the error.  Laravel 10.33, EE 7.3.14.

**Comment by litzinger** [comment]
Noting that I just commented out that `throw` line and everything started working fine again. Clearly not the fix, just a temp work around.

**Comment by bryannielsen** [comment]
Sorry about that! This should be resolved now in 1.2.1 - https://github.com/ExpressionEngine/Coilpack/releases/tag/1.2.1
